steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/voting-app:$COMMIT_SHA', './vote']

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/voting-app:$COMMIT_SHA']

  # Step 3: Deploy to GKE
  #- name: 'gcr.io/cloud-builders/kubectl'
    #args: ['apply', '-f', 'kubernetes/voting-app-deployment.yaml']
    #env:
      #- 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      #- 'CLOUDSDK_CONTAINER_CLUSTER=example-cluster'
  # Step 3: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/hban1116/example-voting-app.git', '/workspace/repo']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Contents of /workspace/repo:"
        ls -la /workspace/repo
    
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git config --global user.email "harshitbansal1116@gmail.com"
        git config --global user.name "hban1116"
        git remote set-url origin https://harshitbansal1116@gmail.com:Winwinwin@321@github.com/hban1116/example-voting-app.git
    dir: '/workspace/repo'
  # Step 4: Update the deployment YAML file with the new image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's#image: dockersamples/examplevotingapp_vote#image: gcr.io/$PROJECT_ID/voting-app:$COMMIT_SHA#g' /workspace/repo/k8s-specifications/vote-deployment.yaml

  # Step 5: Commit and push the changes back to the repository
  - name: 'gcr.io/cloud-builders/git'
    dir: '/workspace/repo'
    args:
      - add
      - 'k8s-specifications/vote-deployment.yaml'
  - name: 'gcr.io/cloud-builders/git'
    dir: '/workspace/repo'
    args:
      - commit
      - '-m'
      - 'Update voting-app image to gcr.io/$PROJECT_ID/voting-app:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
  - name: 'gcr.io/cloud-builders/git'
    dir: '/workspace/repo'
    args:
      - push
      - origin
       # or the appropriate branch

options:
  logging: CLOUD_LOGGING_ONLY
