steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/voting-app:$COMMIT_SHA', './vote']

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/voting-app:$COMMIT_SHA']

  # Step 3: Deploy to GKE
  #- name: 'gcr.io/cloud-builders/kubectl'
    #args: ['apply', '-f', 'kubernetes/voting-app-deployment.yaml']
    #env:
      #- 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      #- 'CLOUDSDK_CONTAINER_CLUSTER=example-cluster'
  # Step 3: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/hban1116/example-voting-app.git', '/workspace/repo']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Contents of /workspace/repo:"
        ls -la /workspace/repo
    
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x /workspace/repo/update_and_push.sh
        /workspace/repo/update_and_push.sh

options:
  logging: CLOUD_LOGGING_ONLY
