steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/voting-app:$BUILD_ID', './vote']

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/voting-app:$BUILD_ID']

  # Step 3: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/hban1116/example-voting-app.git', '/workspace/repo']

  # Step 4: List contents of the repository
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Contents of /workspace/repo:"
        ls -la /workspace/repo

  # Step 5: Run the update and push script with the build ID
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x /workspace/repo/vote/update_and_push.sh
        /workspace/repo/vote/update_and_push.sh $BUILD_ID

options:
  logging: CLOUD_LOGGING_ONLY
